language: node_js
env:
  global:
    - PATH=$HOME/.local/bin:$PATH
before_install:
  - pip install --user awscli
install:
  - npm install
  - npm run bootstrap
  - npm run build
script:
  - npm run test:ci
before_deploy:
  - cd packages/tracker && zip -rq ../../bitstreamy-tracker.zip * && cd ../../
deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY_ID
    secret_access_key: $AWS_SECRET_ACCESS_KEY
    bucket: bitstreamy-webapp
    skip_cleanup: true
    local_dir: packages/webapp/build
    region: eu-west-1
  - provider: elasticbeanstalk
    access_key_id: $AWS_ACCESS_KEY_ID
    secret_access_key: $AWS_SECRET_ACCESS_KEY
    region: "eu-west-1"
    app: "bitstreamy-tracker"
    env: "bitstreamy-tracker-prod"
    bucket_name: "bitstreamy-tracker-prod"
    zip_file: "bitstreamy-tracker.zip"
    skip_cleanup: true
after_deploy:
  - aws configure set preview.cloudfront true
  - aws cloudfront create-invalidation --distribution-id $CLOUDFRONT_DISTRIBUTION_ID --paths "/*"
