version: 0.2
env:
  parameter-store:
    CLOUDFRONT_DISTRIBUTION_ID: /CodeBuild/CLOUDFRONT_DISTRIBUTION_ID
    NPM_TOKEN: /CodeBuild/NPM_TOKEN
phases:
  install:
    runtime-versions:
      nodejs: 10
    commands:
      - npm install
  pre_build:
    commands:
      - npm run bootstrap
  build:
    commands:
      - npm run build
  post_build:
    commands:
      - npm run test
      - aws s3 sync packages/webapp/build/ s3://www.bitstreamy.com --delete
      - aws configure set preview.cloudfront true
      - aws cloudfront create-invalidation --distribution-id $CLOUDFRONT_DISTRIBUTION_ID --paths "/*"
      - npm run publish
artifacts:
  files:
    - appspec.yml
    - scripts/**/*
    - packages/api/**/*
    - packages/tracker/**/*
