version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 10
    commands:
      - npm install
  pre_build:
    commands:
      - npm run bootstrap
  build:
    commands:
      - npm run build
  post_build:
    commands:
      - npm run test
artifacts:
  files:
    - appspec.yml
    - packages/webapp/build/**/*
    - packages/api/**/*
    - packages/tracker/**/*
