version: "3"
services:
  db:
    image: "postgres:11-alpine"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: bitstreamy
      POSTGRES_PASSWORD: bitstreamy
      POSTGRES_DB: bitstreamy
